"""phase7_review_dispute_indexes

Revision ID: 10183b1f6b80
Revises: 262ba4479d09
Create Date: 2026-09-25 12:59:53.361291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10183b1f6b80'
down_revision: Union[str, None] = '262ba4479d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_disputes_status_created_at', 'disputes', ['status', 'created_at'], unique=False)
    op.create_index('ix_reviews_provider_id_created_at', 'reviews', ['provider_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_provider_id_created_at', table_name='reviews')
    op.drop_index('ix_disputes_status_created_at', table_name='disputes')
    # ### end Alembic commands ###
