"""phase7_notification_indexes

Revision ID: 262ba4479d09
Revises: 2e17fa8d17fc
Create Date: 2026-09-24 17:10:22.381030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262ba4479d09'
down_revision: Union[str, None] = '2e17fa8d17fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    # ### end Alembic commands ###
