"""phase5_provider_verification_staff

Revision ID: 4a077507981d
Revises: 554a5b327557
Create Date: 2026-09-23 13:09:24.234368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a077507981d'
down_revision: Union[str, None] = '554a5b327557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_provider_staff_user')
    )
    op.create_index(op.f('ix_provider_staff_members_id'), 'provider_staff_members', ['id'], unique=False)
    op.create_index(op.f('ix_provider_staff_members_provider_id'), 'provider_staff_members', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_staff_members_user_id'), 'provider_staff_members', ['user_id'], unique=False)
    op.add_column('providers', sa.Column('verification_status', sa.String(length=20), nullable=False, server_default='UNVERIFIED'))
    op.add_column('providers', sa.Column('business_registration_number', sa.String(length=100), nullable=True))
    op.add_column('providers', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('providers', sa.Column('verification_notes', sa.String(length=1000), nullable=True))
    op.add_column('providers', sa.Column('verification_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('providers', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_providers_verification_status'), 'providers', ['verification_status'], unique=False)
    op.drop_column('providers', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_providers_verification_status'), table_name='providers')
    op.drop_column('providers', 'verified_at')
    op.drop_column('providers', 'verification_submitted_at')
    op.drop_column('providers', 'verification_notes')
    op.drop_column('providers', 'gst_number')
    op.drop_column('providers', 'business_registration_number')
    op.drop_column('providers', 'verification_status')
    op.drop_index(op.f('ix_provider_staff_members_user_id'), table_name='provider_staff_members')
    op.drop_index(op.f('ix_provider_staff_members_provider_id'), table_name='provider_staff_members')
    op.drop_index(op.f('ix_provider_staff_members_id'), table_name='provider_staff_members')
    op.drop_table('provider_staff_members')
    # ### end Alembic commands ###
