"""phase2_stations_fuel_queue

Revision ID: dfa8b6ea5629
Revises: 7ddefec23ca4
Create Date: 2026-09-22 16:41:22.890701

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa8b6ea5629'
down_revision: Union[str, None] = '7ddefec23ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('is_24_hours', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fuel_stations_location', 'fuel_stations', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_fuel_stations_city'), 'fuel_stations', ['city'], unique=False)
    op.create_index(op.f('ix_fuel_stations_id'), 'fuel_stations', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_stations_locality'), 'fuel_stations', ['locality'], unique=False)
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_fuel_types_id'), 'fuel_types', ['id'], unique=False)
    op.create_table('favorite_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'station_id', name='uq_favorite_station')
    )
    op.create_index(op.f('ix_favorite_stations_id'), 'favorite_stations', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_stations_station_id'), 'favorite_stations', ['station_id'], unique=False)
    op.create_index(op.f('ix_favorite_stations_user_id'), 'favorite_stations', ['user_id'], unique=False)
    op.create_table('fuel_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'fuel_type_id', name='uq_fuel_availability_station_fuel_type')
    )
    op.create_index(op.f('ix_fuel_availability_fuel_type_id'), 'fuel_availability', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_fuel_availability_id'), 'fuel_availability', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_availability_station_id'), 'fuel_availability', ['station_id'], unique=False)
    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'fuel_type_id', name='uq_fuel_price_station_fuel_type')
    )
    op.create_index(op.f('ix_fuel_prices_fuel_type_id'), 'fuel_prices', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_id'), 'fuel_prices', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_station_id'), 'fuel_prices', ['station_id'], unique=False)
    op.create_table('queue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('reporter_latitude', sa.Float(), nullable=True),
    sa.Column('reporter_longitude', sa.Float(), nullable=True),
    sa.Column('is_verified_partner_report', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_reports_id'), 'queue_reports', ['id'], unique=False)
    op.create_index(op.f('ix_queue_reports_reported_by_id'), 'queue_reports', ['reported_by_id'], unique=False)
    op.create_index(op.f('ix_queue_reports_station_id'), 'queue_reports', ['station_id'], unique=False)
    op.create_table('station_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'facility_code', name='uq_station_facility')
    )
    op.create_index(op.f('ix_station_facilities_id'), 'station_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_station_facilities_station_id'), 'station_facilities', ['station_id'], unique=False)
    op.create_table('queue_report_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_report_id', sa.Integer(), nullable=False),
    sa.Column('flagged_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flagged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['queue_report_id'], ['queue_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_report_id', 'flagged_by_id', name='uq_queue_report_flag')
    )
    op.create_index(op.f('ix_queue_report_flags_id'), 'queue_report_flags', ['id'], unique=False)
    op.create_index(op.f('ix_queue_report_flags_queue_report_id'), 'queue_report_flags', ['queue_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_report_flags_queue_report_id'), table_name='queue_report_flags')
    op.drop_index(op.f('ix_queue_report_flags_id'), table_name='queue_report_flags')
    op.drop_table('queue_report_flags')
    op.drop_index(op.f('ix_station_facilities_station_id'), table_name='station_facilities')
    op.drop_index(op.f('ix_station_facilities_id'), table_name='station_facilities')
    op.drop_table('station_facilities')
    op.drop_index(op.f('ix_queue_reports_station_id'), table_name='queue_reports')
    op.drop_index(op.f('ix_queue_reports_reported_by_id'), table_name='queue_reports')
    op.drop_index(op.f('ix_queue_reports_id'), table_name='queue_reports')
    op.drop_table('queue_reports')
    op.drop_index(op.f('ix_fuel_prices_station_id'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_id'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_fuel_type_id'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    op.drop_index(op.f('ix_fuel_availability_station_id'), table_name='fuel_availability')
    op.drop_index(op.f('ix_fuel_availability_id'), table_name='fuel_availability')
    op.drop_index(op.f('ix_fuel_availability_fuel_type_id'), table_name='fuel_availability')
    op.drop_table('fuel_availability')
    op.drop_index(op.f('ix_favorite_stations_user_id'), table_name='favorite_stations')
    op.drop_index(op.f('ix_favorite_stations_station_id'), table_name='favorite_stations')
    op.drop_index(op.f('ix_favorite_stations_id'), table_name='favorite_stations')
    op.drop_table('favorite_stations')
    op.drop_index(op.f('ix_fuel_types_id'), table_name='fuel_types')
    op.drop_table('fuel_types')
    op.drop_index(op.f('ix_fuel_stations_locality'), table_name='fuel_stations')
    op.drop_index(op.f('ix_fuel_stations_id'), table_name='fuel_stations')
    op.drop_index(op.f('ix_fuel_stations_city'), table_name='fuel_stations')
    op.drop_index('idx_fuel_stations_location', table_name='fuel_stations', postgresql_using='gist')
    op.drop_table('fuel_stations')
    # ### end Alembic commands ###
