"""phase8_sponsored_listings_fleet_pro

Revision ID: f4ee1d8ec079
Revises: 10183b1f6b80
Create Date: 2026-09-26 12:27:32.822696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ee1d8ec079'
down_revision: Union[str, None] = '10183b1f6b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_accounts_id'), 'fleet_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_fleet_accounts_owner_user_id'), 'fleet_accounts', ['owner_user_id'], unique=False)
    op.create_table('fleet_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fleet_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fleet_account_id'], ['fleet_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_account_id', 'user_id', name='uq_fleet_member')
    )
    op.create_index(op.f('ix_fleet_members_fleet_account_id'), 'fleet_members', ['fleet_account_id'], unique=False)
    op.create_index(op.f('ix_fleet_members_id'), 'fleet_members', ['id'], unique=False)
    op.create_index(op.f('ix_fleet_members_user_id'), 'fleet_members', ['user_id'], unique=False)
    op.add_column('providers', sa.Column('is_sponsored', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('providers', 'is_sponsored', server_default=None)
    op.create_index(op.f('ix_providers_is_sponsored'), 'providers', ['is_sponsored'], unique=False)
    op.add_column('vehicles', sa.Column('fleet_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_fleet_account_id'), 'vehicles', ['fleet_account_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'fleet_accounts', ['fleet_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_fleet_account_id'), table_name='vehicles')
    op.drop_column('vehicles', 'fleet_account_id')
    op.drop_index(op.f('ix_providers_is_sponsored'), table_name='providers')
    op.drop_column('providers', 'is_sponsored')
    op.drop_index(op.f('ix_fleet_members_user_id'), table_name='fleet_members')
    op.drop_index(op.f('ix_fleet_members_id'), table_name='fleet_members')
    op.drop_index(op.f('ix_fleet_members_fleet_account_id'), table_name='fleet_members')
    op.drop_table('fleet_members')
    op.drop_index(op.f('ix_fleet_accounts_owner_user_id'), table_name='fleet_accounts')
    op.drop_index(op.f('ix_fleet_accounts_id'), table_name='fleet_accounts')
    op.drop_table('fleet_accounts')
    # ### end Alembic commands ###
